pactflow/docs.pactflow.io

website/yarn.lock

also upgraded docusaurus to fix: https://snyk.io/vuln/SNYK-JS-REMARKABLE-174639

chore: fix Regular Expression Denial of Service in underscore.string

---

scripts/build-site.sh
scripts/deploy-infra.sh
templates/infra.yaml

* The relocation of pactflow.io domain records to the prod account
means parity in environments. Removing need to create resources based
on environment

chore: update domain configurations and environment association

---

docs/permissions/api-tokens.md
docs/permissions/permissions.md
docs/permissions/predefined-roles.md
website/i18n/en.json
website/sidebars.json

These docs are accurate for the code we currently have in prod. They make no mention of editing roles or role assignments.

chore: add roles and permissions docs

---

website/docs/docs/permissions/permissions.md
website/docs/docs/user-interface/settings/teams.md

I think you can tell whether or not you have a workable design by how little documentation you need to add!

chore: add information about team permissions and default team

---

website/docs/docs/workshops/ci-cd/workshop/02_how_to_break_everything.md

Gramar correction Update 02_how_to_break_everything.md

---

website/docs/docs/bi-directional-contract-testing/contracts/oas.md
website/docs/docs/bi-directional-contract-testing/provider.md

Content reshuffled a bit from https://github.com/pactflow/example-bi-directional-provider-postman/pull/13

docs: add bdct provider upload initial docs

---

website/docs/docs/user-interface/settings/authentication.md

Thanks to @sreenivasnarayan for working this out!

chore: add docs for when no name is coming through from github

---

website/docs/docs/getting-started.mdx
website/docs/docs/tutorials.md
website/docs/docs/workshops/bi-directional-contract-testing.md
website/docs/docs/workshops/introduction.md
website/docs/docs/workshops/quick_starts/bdc.mdx
website/sidebars.js

Reverts pactflow/docs.pactflow.io#121
Will update with Killercoda refs https://killercoda.com/pactflow

Revert "chore: remove katacoda as the platform has been decommissioned"

---

website/docs/docs/on-premises/license.md

RE: https://pact-foundation.slack.com/archives/G01BE91P3U0/p1658430184859869

docs: document how to specify custom license file location

---

website/docs/docs/on-premises/environment-variables.md

Added some further description to help on prem users get started with auth and not using the basic auth user.

chore: PACT-148 update basic auth doc

---

website/docs/docs/on-premises/releases/1.19.2.md
website/notices/2022-08-24-on-premises-1.19.2.md
website/sidebars.js

release notes for on prem patch

chore(on-prem): fix release

---

website/docs/docs/bi-directional-contract-testing.md

docs: making name changes

---

website/docs/docs/scim/okta.md

SCIM Okta - minor typo

---

website/package.json
website/yarn.lock

Reverts pactflow/docs.pactflow.io#191

Revert "chore(deps): bump @mdx-js/react from 1.6.22 to 2.2.1 in /website"

---

website/docs/docs/bi-directional-contract-testing/provider.md

Very tiny fix to address broken link mentioned by customer here https://smartbear.atlassian.net/browse/CC-28997

fix: fix broken doc link

---

website/docs/docs/on-premises/releases/1.22.0.md
website/notices/2023-02-13-on-premises-1.22.0.md
website/sidebars.js

chore: onprem 1.22.0 release notes

---

website/docs/docs/how_to.md

Minor change to correct terminology for this guide.

chore: PACT-701 change version number to SHA

---

website/docs/docs/on-premises/support-policy.md

As per https://smartbear.atlassian.net/wiki/spaces/PACT/pages/3415638049/2023-02-16+Meeting+notes.

docs: improve on-premises support policy

---

website/docs/docs/on-premises/maintenance/database.md

chore: add note to indicate same docker tag must be used for clean task as app

---

website/docs/docs/scim/main.md
website/docs/docs/scim/okta.md

Added note about permissions required
Also added note about the importance of having the userName set, otherwise the integration will not work correctly.

chore: add note about permissions required and the userName attribute in the SCIM docs

---

website/docs/docs/on-premises/scim.md
website/docs/docs/permissions/permissions.md
website/docs/docs/permissions/predefined-roles.md
website/docs/docs/scim/main.md
website/docs/docs/scim/okta.md

feat: update docs with SCIM role info

---

website/docs/docs/workshops/quick_starts/bdc.mdx

I was reading this doc and thought I'd put up a PR with typos and small grammar fixes that I bumped into.

Fix typos and grammar in bdc.mdx

---

website/docs/docs/tutorials.md
website/docs/docs/workshops/bi-directional/step11.md
website/docusaurus.config.js

Fixes some broken links identified by @AnubhutiShrivastava

chore: fix broken links, setup redirect for API token

---

website/docs/docs/on-premises/environment-variables.md
website/docs/docs/on-premises/releases/1.29.0.md
website/notices/2024-01-30-on-premises-1.29.0.md
website/notices/2024-01-31-on-premises-1.29.0.md
website/sidebars.js

Release 1.29.0

---

website/docusaurus.config.js
website/package.json
website/static/js/fix-location.js
website/yarn.lock

- Add the custom script to remove trailing slash
- Upgrade docusaurus

fix: broken internal links when there is trailing slash

---

website/docs/docs/ai/index.md
website/src/components/AiDownloadTable.js
website/src/components/index.js

Quick docs for our closed beta users. Key feature is the download table that dynamically fetches latest version and then downloads the file for the correct os/arch.

feat: initial ai docs

---

scripts/release/release-notes-onprem.sh

fix: added error handling for jira requests
fix: added a way to automatically infer previous version SHA it finds the last version in docs.pactflow.io and queries this version against pactflow-application to check matching git tag in pactflow-application, then it finds the git SHA of that tag and uses it for finding the commits
fix: increased the git clone time period to 6 months
also fixed PROD_TAG coming as null

fix onprem release script

---

scripts/release/release-notes-onprem.sh
website/docs/docs/on-premises/environment-variables.md
website/docs/docs/on-premises/releases/1.31.0.md
website/notices/2024-08-22-on-premises-1.31.0.md
website/sidebars.js

JIRA https://smartbear.atlassian.net/browse/PACT-2280

chore: add release notes for 1.31.0

---

website/docs/docs/ai/index.md
website/docs/docs/tutorials.md

- add installer help command / list options
- add note about glibc compat and musl alternative
- add killercoda tutorial
- source: https://github.com/pactflow/katacoda-workshops/tree/master/pactflow-ai
- tutorial: https://killercoda.com/pactflow/scenario/pactflow-ai

docs: update pactflow-ai install instructions / add interactive tutorial

---

website/docs/docs/on-premises/releases/1.33.0.md
website/notices/2024-09-18-on-premises-1.33.0.md
website/sidebars.js

JIRA https://smartbear.atlassian.net/browse/PACT-2497

chore: release notes for 1.33.0

---

website/docs/docs/on-premises/releases/1.34.0.md
website/notices/2024-10-22-on-premises-1.34.0.md
website/sidebars.js

JIRA https://smartbear.atlassian.net/browse/PACT-2612

chore: onprem release 1.34.0

---

website/docs/docs/ai/index.md

docs: add docs for PoSH users to install AI tools

---

website/docs/docs/on-premises/releases/1.35.0.md
website/notices/2024-11-18-on-premises-1.35.0.md
website/sidebars.js

https://smartbear.atlassian.net/browse/PACT-2750

chore: on-prem release notes for 1.35.0

---

website/docs/docs/ai/index.md
website/docs/docs/permissions/permissions.md
website/docs/docs/permissions/predefined-roles.md

docs: AI RBAC permissions

---

website/docs/docs/workshops/bi-directional/pre_requisites.md
website/docs/docs/workshops/bi-directional/step5.md

The workshop doesn't have the Github link. Also step 5 is a bit mysterious

Added hyperlink to Github

---

scripts/release/release-notes-onprem.sh
website/docs/docs/on-premises/releases/1.36.0.md
website/notices/2025-01-17-on-premises-1.36.0.md
website/sidebars.js

- updated the script to be more rescilient to retries and debugging
- updated the parsing to have better parse error handling
- the notes now accurately compile JIRAs without notes
- added JIRA links to the notes ( for easy access, to be removed while reviewing the docs )

chore: Onprem release 1.36.0

---

website/docs/docs/bi-directional-contract-testing/contracts/oas/changelog.md
website/docs/docs/bi-directional-contract-testing/contracts/oas/configuration.md
website/docs/docs/bi-directional-contract-testing/contracts/oas/features.md
website/sidebars.js

[PACT-3067](https://smartbear.atlassian.net/browse/PACT-3067)
[PACT-3067]: https://smartbear.atlassian.net/browse/PACT-3067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BDCT Updates (OPC)

---

website/docs/docs/ai/index.md
website/docs/docs/ai/using.md
website/docs/docs/tutorials.md

1. Add additional languages
2. Add test templates killercoda tutorial
PACT-4122

docs: ai updates

---

website/docs/docs/ai/index.md
website/docs/docs/ai/using.md

docs: code review
