pactflow/docs.pactflow.io

docs/workshops/ci-cd/set-up-ci/00_prerequisites.md
docs/workshops/ci-cd/workshop/00_prerequisites.md
website/package.json
website/scripts/copy-index-pages.sh

Copies `foo/index.html` to `foo/index/index.html` so that the generated `foo/index` link works.
Every .html page is copied to a directory with the same name, and an index page is put within that directory, so that both '/foo' and 'foo.html' work.
For some reason this is explicitly disabled in the generate script, but the URL generation script (which I haven't looked in to) does not take this into account. Rather than hacking the JS, it seemed easiest to just copy the index files to the correct place, the way all the other files are.
Fixes: https://github.com/pactflow/docs.pactflow.io/issues/8

fix: allow foo/index to be mapped to foo/index/index.html

---

website/docs/docs/on-premises/environment-variables.md
website/docs/docs/on-premises/releases/1.11.1.md
website/docs/docs/on-premises/releases/1.12.0.md
website/docs/docs/permissions/predefined-roles.md
website/docs/docs/user-interface/settings/preferences.md
website/sidebars.js

Things that are deliberately not released or documented as they're not ready yet, either in terms of the code or the documentation:
* environments - until we get team environments working (the link is hidden though the API is accessible)
* OAuth and OIDC
* Anyway config files

chore: update docs for 1.12.0

---

website/docusaurus.config.js

I'm not sure why we ever had this. I definitely added this to our partner docs, I'm wondering if it was copied across during an upgrade or something.
In any case, we definitely want our docs internet searchable. 
I noticed it was the case when I could never search for things I knew only existed in our documentation, and then realised the pages had index exclusions.

chore: allow google to index documentation

---

website/docs/docs/permissions/predefined-roles.md

Originally docs PR had CICD user as having the team version of record deployment and release permission but both admin and CICD roles should have global permission listed.

fix: default CI/CD permission discrepancy

---

website/docs/docs/user-interface/settings/preferences.md

Small update to add the new Operational Notification Contacts into the permissions docs.

feat: add operational notification contacts to the preferences page

---

website/docs/docs/on-premises/security-audit-report.md
website/docs/docs/on-premises/something.md
website/sidebars.js

So we don't have to repeat ourselves each time, we should have a page that lists our known vulnerabilities and their mitigations. I'm definitely missing some for bootstrap, but I'll add them as they come up. The most recent people who complained about them didn't include the CVEs.
* What should the page be called?
* Any extra info?

chore: add docs for known vulnerabilities

---

website/docs/docs/user-interface/bi-directional.md

This is how I'm currently planning on implementing the bdc matrix. The reason for doing it this way is
* there will be `unique consumer contract versions count * unique provider contract versions count` comparisons to be generated, and they can't all be done on the fly, because the comparison takes a non-trivial amount of time, shelling out to a separate process.
* the matrix UI needs a set of default data to show (currently - though I'd really like this page to be made redundant by the new UI)
* can-i-deploy has to return an accurate answer.

chore: update bdc matrix docs

---

website/docs/docs/bi-directional-contract-testing/contracts/pact.md
website/docusaurus.config.js

* Update the compatibility section to show that pact spec V3 is now supported for BDCT, and note for when on-prem will support this

chore: update supported pact verification versions

---

website/docs/docs/getting-started.mdx
website/docs/docs/on-premises/database.md
website/docs/docs/on-premises/installation/migrating-from-pact-broker.md
website/sidebars.js

This PR adds a detailed section on how to migrate existing Pact Broker db for on-prem users. I have also added a brief overview of the process to the 'Getting Started' section for SAAS users, who will need to contact us to do this as part of their onboarding.
We will need to follow up with some process notes on how to do this for our own reference for SAAS users.
I'll also update the customer care team issue index to flag this with them, any tickets with this type of query will need to be assigned to us.

feat: pact broker migration docs PACT-158

---

website/docs/docs/bi-directional-contract-testing/contracts/keyword-support.md
website/docs/docs/bi-directional-contract-testing/contracts/oas.md
website/sidebars.js

This doc update is to add additional notes around keyword support and the nullable field issue which was recently brought up by a customer. These can be used by customers and devs when doing support to guide how and when these keywords are used.
In the future we would like to work on improving some of these limitations of the swagger-mock-validator.

chore: update docs about keyword support PACT-235

---

Dockerfile
docker-compose.yml

The docker-compose build was running as the folder in the docker file doesn't exist.
Hot reloading working, but mounting the docs folders in the container

fix: update docker build to work / hot reload

---

website/docs/docs/permissions/predefined-roles.md

Update the docs to include the SwaggerHub role which will be used in the SwaggerHub integration.

chore: add SwaggerHub role to docs

---

README.md

The link in the README was being directed to
https://github.com/pactflow/docs.pactflow.io/blob/master/Docusaurus, which doesn't exist. Now the link goes to https://docusaurus.io/docs/, with the Docusaurus text being displayed

Fixing Docusaurus link in README

---

website/docs/docs/getting-started.mdx

In the Providers examples, the .NET example use the "C++" name, instead of .NET

Fix reference to C++ instead of .NET in Getting Started

---

website/docs/docs/workshops/ci-cd/workshop/05_implementing_the_provider_changes.md

Previously we had a command (test_webhook) to test a specific pact uploaded to the broker. We removed this command from the MakeFile but we forgot to upload the tutorial docs to use the new command (ci_webhook) that allows you to test the same thing locally. This commit replaces that command in the ci/cd workshop tutorial to be able to test the pact properly.
Closes #221.
Try to run the `ci_webhook` command with a specific PACT_URL to ensure that the command does what's supposed to do for the workshop (testing locally the provider against that pact).

Update ci/cd workshop docs with ci_webhook command

---

website/docs/docs/billing.md
website/docs/docs/getting-started.mdx
website/docs/docs/login.md
website/docs/docs/on-premises.md
website/docs/docs/on-premises/docker-compose-example.md
website/docs/docs/on-premises/installation/checklist.md
website/docs/docs/on-premises/license.md
website/docs/docs/on-premises/releases/1.10.0.md
website/docs/docs/on-premises/security-audit-report.md
website/docs/docs/on-premises/support-policy.md
website/docs/docs/user-interface/settings/authentication.md
website/docs/docs/webhooks.md
website/notices/2022-03-28-pact-dius-com-au-decommission.md

Redirects most support@pactflow.io references to our new support form here: https://support.smartbear.com/pactflow/message/
Minor updates to other references as required (i.e. licenses should go to the customer's Account Manager)

chore: replace support email with new web form

---

website/docs/docs/user-interface/settings/teams.md

This PR updates the teams doc to reflect the clean up process that happens in the DB when a team is deleted. The webhooks and secrets that were associated with the team are not deleted, instead they revert to being editable only by admins.

chore: PACT-853 update delete team docs

---

website/docs/docs/on-premises/environment-variables.md
website/docs/docs/on-premises/releases/1.26.0.md
website/notices/2023-08-07-on-premises-1.26.0.md
website/sidebars.js

Release notes generated from script, updated with SCIM role migration notes.

chore: release notes for 1.26.0

---

website/docs/docs/authentication/main.md
website/docs/docs/user-interface/settings/preferences.md

PACT-1467
See also https://github.com/pactflow/pactflow-application/pull/1427.

docs: add consolidate users system preference

---

.github/workflows/crawl-site.yml

We are out of space in our Algolia plan and this job run on push is causing GH checks to fail unnecessarily for unrelated changes.
This disables it, albeit able to be triggered by workflow_dispatch if/when resolved

chore(ci): disable cron and push crawl search docs job

---

website/docs/docs/getting-started.mdx

- consumer side recommend cli tools
- remove go/.net consumer publishing snippets (removed from current packages)
- provider
- updated .NET snippet to pact-net V4.
notes: docker verifier should be updated, to use the pact-core-mock-server, which is the new native verifier built in rust.
- image https://hub.docker.com/r/pactfoundation/pact-ref-verifier
- guidance on docs.pact.io site https://docs.pact.io/implementation_guides/cli#distributions

chore: fix #303 - update getting started - recommend cli

---

website/docs/docs/examples/aws/sns/consumer/readme.md
website/docs/docs/examples/dotnet/consumer/readme.md
website/docs/docs/examples/dotnet/provider/readme.md
website/docs/docs/examples/golang/consumer/readme.md
website/docs/docs/examples/golang/provider/readme.md
website/docs/docs/examples/java/consumer/graphql/readme.md
website/docs/docs/examples/java/provider-springboot/readme.md
website/docs/docs/examples/js/consumer/readme.md
website/docs/docs/examples/kafka/java/consumer.md
website/docs/docs/examples/kafka/java/provider.md
website/docs/docs/examples/soap/java/consumer.md
website/docs/docs/examples/soap/java/provider.md

The org token `GHTOKENFORTRIGGERINGPACTDOCSUPDATE` is unable to access this repo since PactFlow org switch to SSO and therefore this job was manually triggered to pickup readme updates on example repos

chore: synced all docs

---

website/docs/docs/bi-directional-contract-testing/contracts/oas/features.md

We now support `x-www-form-urlencoded` bodies.
PACT-1814

docs: update form support for BDCT

---

.buildkite/pipeline.yml

Make use of the new, automatically updated, images from the `build-container` repository which have been moved under a new namespace.
The `node/serverless` image used as it has AWS CLI and is pushed to production. The script has been updated to make sure that `yarn` is installed.
Ref: pactflow/build-containers#36
Ref: PACT-4295

chore(ci): use new build-container image
